### PR TITLE
added new section x-ray-ecr

### PR DESCRIPTION
**Pull request by enghwa**
AWS X-Ray for python Flask App and nodejs Express microservices.

### CODE REVIEW

**Comment by arun-gupta** [comment]
This is really cool!

Is there a hard dependency on ECR or can Docker Hub be used as well? I was thinking more in the line of the directory name to include `ecr`.

**Comment by enghwa** [comment]
No hard dependency at all. I started off as dockerhub actually.

**Comment by arun-gupta** [comment]
Can you change the directory name to `x-ray` then?

I'd love to test it out after merging.

**Comment by enghwa** [comment]
done

**Comment by arun-gupta** [comment]
@enghwa https://github.com/arun-gupta/kubernetes-aws-workshop/blob/master/x-ray/images/xray1.png shows `AWS::ECS::Container`. Can you update the image to use `k8s` instead?

**Comment by enghwa** [comment]
@arun-gupta  right now AWS X-ray has no k8s plugin.. hence it can only show EC2/Beanstalk/or ECS.  the offending line is at 18:
https://github.com/arun-gupta/kubernetes-aws-workshop/blob/master/x-ray/nodejs-microservices/webapp/server.js
Removing XRay.plugins.ECSPlugin will remove the text `AWS::ECS::Container` but then it will not show the pod (container)/host relationship in the XRay trace UI.

**Comment by arun-gupta** [comment]
Thanks @enghwa, checking with X-Ray team.

**Pull request merged**
