### PR TITLE
Add Cloudformation for kubernetes deployment w/out ALB

### PR DESCRIPTION
**Pull request by cloudymind**
This cloudformation will deploy a kubernetes cluster with a single master and variable nodes. It will also attach a weave or calico networking provider. (ALB implementation coming soon)

*Minor edit: Move yaml for deployment concepts.

### CODE REVIEW

**Comment by arun-gupta** [comment]
@cloudymind The command to create the cluster is missing?

**Comment by cloudymind** [comment]
Do you mean the command to deploy the cf? The only thing this doesn't do is create a sample service. Otherwise, it's just this: https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/

**Comment by arun-gupta** [comment]
Merging this one, let's add instructions at https://github.com/arun-gupta/kubernetes-aws-workshop/issues/76

**Comment by cloudymind** [comment]
cool. will do

**Pull request merged**
